### ISSUE TITLE
Antivirus thinks it contains malware??

### ISSUE THREAD

**Issue by Eliiia** [daemondevin/DiscordPortable#2]
I tried to launch it, but my autovirus automatically takes it and tells me it's Malware. I'll have to disable it for 5 minutes...

**Comment by daemondevin** [comment]
False positive.. 

You can review all the source code that this portable is compiled with and the generator used to package it can be reviewed by visiting:
https://github.com/daemondevin/pac-man

**Comment by Eliiia** [comment]
Yeah, i know that it doesn't have malware, but the antivirus says that it has a virus, which would get some people away from trying to use it and would instead abandon it.

**Comment by daemondevin** [comment]
I can understand your concern however I'd like to share with you and any others reading this, I'm not making portable applications for those who do not know what they are doing. Moreover, if these people abandon my project because they do not understand or aren't sure if they should trust my work.. let them. My work is not meant for these individuals to begin with.

Power to the power user.. Lol.
