### ISSUE TITLE
DiscordPortable is detected as malware by Avast

### ISSUE THREAD

**Issue by SSUPII** [daemondevin/DiscordPortable#3]
Avast detects DiscordPortable.exe as infected by FileRepMetagen (that is very likely meaning that the file has a bad reputation) when runned or when doing a right-click scan.

VirurTotal detections https://www.virustotal.com/#/file/8a3f5c6c80442f06149f753b01f682340905589669c3d9200834d97893e8369d/detection

**Comment by fogoat** [comment]
McAfee deleted the latest EXE as Artemis detection. :(

**Comment by ghost** [comment]
Is it lie?

**Comment by daemondevin** [comment]
Please, instead of wasting your energy coming here and asking wheather or not this is actually a virus or some kind of malware.. use your energy to tell the people behind these antivirus' that said executable file is a false-positive. This would save my project, save your time and energy, and save my wits in the long run by not having to repeatedly reassure you people of it's validity.

Guys, remember that GitHub is an open source forum. Which means that the code that created these files are available to the public for review.. the code to the executable file at question is in this very repository. Have a look for yourselves. I encourage you to do so ..please; for the love of God just use your brains for once and review the fucking code people!
